"""Add not_interested_reason to favorites

Revision ID: 06ac8c19c148
Revises: 67cb51f1fb58
Create Date: 2026-03-22 09:43:22.689799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ac8c19c148'
down_revision = '67cb51f1fb58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('not_interested_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'not_interested_reason')
    # ### end Alembic commands ###
