"""Add interested_reason to favorites

Revision ID: 12ab909daf4e
Revises: 082f810f605a
Create Date: 2026-03-22 19:27:56.238340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ab909daf4e'
down_revision = '082f810f605a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('interested_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'interested_reason')
    # ### end Alembic commands ###
