"""Add area_name to rentals table

Revision ID: 082f810f605a
Revises: 06ac8c19c148
Create Date: 2026-03-22 10:36:53.990436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082f810f605a'
down_revision = '06ac8c19c148'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('area_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'area_name')
    # ### end Alembic commands ###
