"""Add state tracking to favorites

Revision ID: 3115b290abd7
Revises: a30b58ee2c41
Create Date: 2026-03-21 21:45:30.278243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3115b290abd7'
down_revision = 'a30b58ee2c41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults for existing rows
    op.add_column('favorites', sa.Column('current_state', sa.String(), server_default='interested', nullable=False))
    op.add_column('favorites', sa.Column('showing_datetime', sa.DateTime(), nullable=True))
    op.add_column('favorites', sa.Column('state_updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'state_updated_at')
    op.drop_column('favorites', 'showing_datetime')
    op.drop_column('favorites', 'current_state')
    # ### end Alembic commands ###
