"""Add applied_reason and viewed_reason to favorites

Revision ID: 875c6b5df737
Revises: 12ab909daf4e
Create Date: 2026-03-22 19:42:57.289319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875c6b5df737'
down_revision = '12ab909daf4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('applied_reason', sa.String(), nullable=True))
    op.add_column('favorites', sa.Column('viewed_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'viewed_reason')
    op.drop_column('favorites', 'applied_reason')
    # ### end Alembic commands ###
