"""Add searches and collaboration features

Revision ID: 4f721ce2c32c
Revises: 875c6b5df737
Create Date: 2026-03-22 21:16:40.820684

"""
from alembic import op
import sqlalchemy as sa
import uuid
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '4f721ce2c32c'
down_revision = '875c6b5df737'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('search_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='memberrole'), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('favorites', sa.Column('search_id', sa.UUID(), nullable=True))

    # Migrate existing favorites to default searches for each user
    connection = op.get_bind()

    # Get all users who have favorites
    users_with_favorites = connection.execute(
        text("SELECT DISTINCT user_id FROM favorites")
    ).fetchall()

    for user in users_with_favorites:
        user_id = user[0]
        search_id = uuid.uuid4()
        member_id = uuid.uuid4()

        # Create a default search for this user
        connection.execute(
            text("""
                INSERT INTO searches (id, name, description, created_by)
                VALUES (:search_id, 'My Listings', 'Default search migrated from original favorites', :user_id)
            """),
            {"search_id": search_id, "user_id": user_id}
        )

        # Add user as owner of this search
        connection.execute(
            text("""
                INSERT INTO search_members (id, search_id, user_id, role, accepted_at)
                VALUES (:member_id, :search_id, :user_id, 'owner', NOW())
            """),
            {"member_id": member_id, "search_id": search_id, "user_id": user_id}
        )

        # Update all favorites for this user to belong to their default search
        connection.execute(
            text("""
                UPDATE favorites
                SET search_id = :search_id
                WHERE user_id = :user_id
            """),
            {"search_id": search_id, "user_id": user_id}
        )

    # Now make search_id NOT NULL since all existing favorites have been migrated
    if len(users_with_favorites) > 0:
        op.alter_column('favorites', 'search_id', nullable=False)

    op.drop_constraint('uq_user_rental', 'favorites', type_='unique')
    op.create_unique_constraint('uq_user_rental_search', 'favorites', ['user_id', 'rental_id', 'search_id'])
    op.create_foreign_key(None, 'favorites', 'searches', ['search_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint('uq_user_rental_search', 'favorites', type_='unique')
    op.create_unique_constraint('uq_user_rental', 'favorites', ['user_id', 'rental_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('favorites', 'search_id')
    op.drop_table('search_members')
    op.drop_table('search_invitations')
    op.drop_table('searches')
    # ### end Alembic commands ###
