"""Add is_deleted field to favorites

Revision ID: 67cb51f1fb58
Revises: 4a2b3c4d5e6f
Create Date: 2026-03-21 23:03:24.916819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cb51f1fb58'
down_revision = '4a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'is_deleted')
    # ### end Alembic commands ###
