"""Add image_url to rentals table

Revision ID: a30b58ee2c41
Revises: 92f2de0b3fe4
Create Date: 2026-03-21 19:10:07.043011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30b58ee2c41'
down_revision = '92f2de0b3fe4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'image_url')
    # ### end Alembic commands ###
